-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(F.PRICE) as TOTAL_SALES from USED_GOODS_USER U 
INNER JOIN USED_GOODS_BOARD F ON F.WRITER_ID = U.USER_ID
WHERE F.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(F.PRICE) >= 700000
order by SUM(F.PRICE);