-- 2022년 1월에 저자별로 카테고리별 매출액을 구해서 리스트 출력
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(B.PRICE*S.SALES) TOTAL_SALES
FROM BOOK B INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01' 
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC